name: deploy flask

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Copy files to EC2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key

          rsync -avz -e "ssh -i ~/.ssh/ec2_key -o StrictHostKeyChecking=no" ./ \
          ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ubuntu/flask-ec2-demo

      - name: Run Flask App on EC2
        run: |
          ssh -i ~/.ssh/ec2_key -o StrictHostKeyChecking=no \
          ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'

          cd /home/ubuntu/flask-ec2-demo

          source venv/bin/activate

          pip install -r requirements.txt

          pkill gunicorn || true

          nohup gunicorn -w 4 -b 0.0.0.0:5000 app:app > output.log 2>&1 &

          EOF